services:
    db:
        image: "mariadb:bionic"
        container_name: "rathena_db"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "rathenadb:/var/lib/mysql" # save database to local disk
            - "../../sql-files/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ragnarok
        ports:
            - 8080:80
    builder:
        image: "rathena:local"
        container_name: "rathena-builder"
        command: "/rathena/tools/docker/builder.sh"
        volumes:
            - "../../../fROggo-folder:/client"
            - "../..:/rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt" #localdev login-char relation
            - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt" #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            BUILDER_CONFIGURE: "--enable-packetver=20180530 --enable-prere=yes"

    login:
        image: "rathena:local"
        container_name: "rathena-login"
        command: sh -c "/bin/wait-for db:3306 -- /rathena/login-server"
        ports:
            - "6900:6900" # login server
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt" #localdev login-char relation
            - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt" #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
    char:
        image: "rathena:local"
        container_name: "rathena-char"
        command: sh -c "/bin/wait-for db:3306 -- /rathena/char-server"
        ports:
            - "6121:6121" # char server
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt" #localdev login-char relation
            - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt" #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - login
    map:
        image: "rathena:local"
        container_name: "rathena-map"
        command: sh -c "/bin/wait-for db:3306 -- /rathena/map-server"
        ports:
            - "5121:5121" # map server
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt" #localdev login-char relation
            - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt" #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - char
    web:
        image: "rathena:local"
        container_name: "rathena-web"
        command: sh -c "/bin/wait-for db:3306 -- /rathena/web-server"
        ports:
            - "8888:8888" # map server
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt" #localdev login-char relation
            - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt" #localdev char-map relation
            - "./asset/web_conf.txt:/rathena/conf/import/web_conf.txt" #localdev web configuration
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - map

volumes:
    rathenadb:
